# Generated by Django 6.0 on 2025-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Inicio')),
                ('end', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('modality', models.CharField(choices=[('presential', 'Presencial'), ('online', 'Online')], default='presential', max_length=20, verbose_name='Modalidad')),
                ('notes_internal', models.TextField(blank=True, verbose_name='Notas internas')),
                ('notes_for_client', models.TextField(blank=True, verbose_name='Notas visibles para cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('document_id', models.CharField(blank=True, max_length=50, verbose_name='ID / documento (RFC, CURP, etc.)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de la consulta')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Campos dinámicos según el nicho (ej. signos vitales, juzgado, etc.)', verbose_name='Datos extra (dinámicos)')),
                ('visible_to_client', models.BooleanField(default=True, verbose_name='Visible para el cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duración por defecto (minutos)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del negocio')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug público')),
                ('niche', models.CharField(choices=[('doctor', 'Médico general'), ('dentist', 'Dentista'), ('lawyer', 'Abogado'), ('psychologist', 'Psicólogo'), ('coach', 'Coach'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Nich(o)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspaces/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#0f172a', max_length=7, verbose_name='Color secundario')),
                ('accent_color', models.CharField(default='#22c55e', max_length=7, verbose_name='Color acento')),
                ('theme_mode', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10, verbose_name='Modo de tema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dueño'), ('professional', 'Profesional'), ('assistant', 'Asistente / staff'), ('client', 'Cliente / paciente')], max_length=20, verbose_name='Rol en el workspace')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro de workspace',
                'verbose_name_plural': 'Miembros de workspace',
            },
        ),
    ]
