# Generated by Django 6.0 on 2025-12-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='theme_name',
            field=models.CharField(default='light', help_text='Nombre del tema DaisyUI/Tailwind (light, dark, corporate, etc.)', max_length=50, verbose_name='Nombre del tema'),
        ),
    ]
