# Generated by ChatGPT on 2025-09-04
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_client_portal_user_clientinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="portal_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que usa el portal de cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_client_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
