# Generated by Django 6.0 on 2026-01-23 14:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_portal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('on_hold', 'En pausa'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casefiles', to='core.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casefiles', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('note', 'Nota'), ('call', 'Llamada'), ('visit', 'Visita'), ('appointment', 'Cita'), ('document', 'Documento'), ('status', 'Cambio de estado'), ('payment', 'Pago'), ('other', 'Otro')], default='note', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField()),
                ('visible_to_client', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_caseevents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseevents', to='core.workspace')),
                ('casefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.casefile')),
            ],
            options={
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.case_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_caseattachments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseattachments', to='core.workspace')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.caseevent')),
                ('casefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.casefile')),
            ],
        ),
        migrations.AddIndex(
            model_name='casefile',
            index=models.Index(fields=['workspace', 'client', 'status'], name='core_casefi_workspa_c92e40_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['workspace', 'casefile', 'happened_at'], name='core_caseev_workspa_98a88e_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['workspace', 'event_type', 'happened_at'], name='core_caseev_workspa_4e7228_idx'),
        ),
    ]
