# Generated by Django 6.0 on 2026-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_casefile_caseevent_caseattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_video_calls',
            field=models.BooleanField(default=False),
        ),
    ]
