# Generated by Django 6.0 on 2026-02-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workspace_enable_video_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=120, unique=True)),
                ('room_passcode', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='core.appointment')),
            ],
        ),
    ]
