# Generated by Django 6.0 on 2026-02-05 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointmentvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_room',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
